# Numpy

In [4]:
import numpy as np

### creation of ndarray and some basic operations

In [5]:
a = np.array([ 0,  1,  2,  3,  4, "ostrapy", "Jeňa", "Serafim"])

In [6]:
a

array(['0', '1', '2', '3', '4', 'ostrapy', 'Jeňa', 'Serafim'],
      dtype='<U21')

In [7]:
a.reshape(2,4)

array([['0', '1', '2', '3'],
       ['4', 'ostrapy', 'Jeňa', 'Serafim']], dtype='<U21')

In [8]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
type(a)

In [ ]:
a.shape # the dimensions of the array

In [ ]:
a.ndim # the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

In [9]:
a.dtype # an object describing the type of the elements in the array

dtype('int64')

In [10]:
a.itemsize # the size in bytes of each element of the array

8

In [11]:
a.size # the total number of elements of the array

15

In [12]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [14]:
a<5

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
np.sin(a)*10

In [ ]:
np.nan

### Random sampling

https://docs.scipy.org/doc/numpy/reference/routines.random.html

In [ ]:
np.random.standard_normal(50) # Draw samples from a standard Normal distribution (mean=0, stdev=1).

##### And many many other things  ...

# SciPy

SciPy (pronounced "Sigh Pie"[2]) is an open source Python library used for scientific computing and technical computing. (Wikipedia)

Tutorial content:
- Introduction
- Basic functions
- Special functions (scipy.special)
- Integration (scipy.integrate)
- Optimization (scipy.optimize)
- Interpolation (scipy.interpolate)
- Fourier Transforms (scipy.fftpack)
- Signal Processing (scipy.signal)
- Linear Algebra (scipy.linalg)
- Sparse Eigenvalue Problems with ARPACK
- Compressed Sparse Graph Routines (scipy.sparse.csgraph)
- Spatial data structures and algorithms (scipy.spatial)
- Statistics (scipy.stats)
- Multidimensional image processing (scipy.ndimage)
- File IO (scipy.io)