# Numpy

In [1]:
import numpy as np

### np.arange is different from range function

In [2]:
np.arange(15) #creates array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
print(type(np.arange(15)))

<class 'numpy.ndarray'>


In [4]:
print(type(range(15)))

<class 'range'>


### creation of ndarray and some basic operations

In [7]:
a = np.array([ 0,  1,  2,  3,  4, "ostrapy", "Jeňa", "Serafim"])

In [8]:
a

array(['0', '1', '2', '3', '4', 'ostrapy', 'Jeňa', 'Serafim'], 
      dtype='<U21')

In [9]:
a.reshape(2,4)

array([['0', '1', '2', '3'],
       ['4', 'ostrapy', 'Jeňa', 'Serafim']], 
      dtype='<U21')

In [10]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
type(a)

numpy.ndarray

In [12]:
a.shape # the dimensions of the array

(3, 5)

In [13]:
a.ndim # the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

2

In [14]:
a.dtype # an object describing the type of the elements in the array

dtype('int64')

In [15]:
a.itemsize # the size in bytes of each element of the array

8

In [16]:
a.size # the total number of elements of the array

15

In [17]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
a*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [19]:
a<5

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [20]:
np.sin(a)*10

array([[ 0.        ,  8.41470985,  9.09297427,  1.41120008, -7.56802495],
       [-9.58924275, -2.79415498,  6.56986599,  9.89358247,  4.12118485],
       [-5.44021111, -9.99990207, -5.36572918,  4.20167037,  9.90607356]])

In [21]:
np.nan

nan

### Random sampling

https://docs.scipy.org/doc/numpy/reference/routines.random.html

In [22]:
np.random.standard_normal(50) # Draw samples from a standard Normal distribution (mean=0, stdev=1).

array([-0.94156214,  1.61845372, -0.00536878, -1.23230779, -1.57934145,
       -0.05434344, -0.36396644, -0.22351756, -0.52584338, -1.22169109,
        0.29192339, -0.17319506, -1.11857745, -0.75753435,  1.46775529,
       -0.89504181,  1.5498404 ,  1.07895105,  1.0598545 ,  0.04871718,
       -1.07054453,  1.08573506, -1.60169949, -0.8711884 , -1.26919262,
        0.05199907, -1.1411747 , -0.90204042, -1.1152305 ,  1.7196803 ,
       -0.55385852,  1.29752473, -0.41495283,  2.03725518,  0.89392517,
        0.75724893,  0.79489773, -0.4955594 ,  1.71957834, -1.62364643,
        1.04696445,  0.25945789,  0.2511216 , -0.07742537, -0.60644302,
       -1.73308511, -1.83632414, -0.62318279,  1.27959818,  0.38990726])

##### And many many other things  ...

# SciPy

SciPy (pronounced "Sigh Pie"[2]) is an open source Python library used for scientific computing and technical computing. (Wikipedia)

Tutorial content:
- Introduction
- Basic functions
- Special functions (scipy.special)
- Integration (scipy.integrate)
- Optimization (scipy.optimize)
- Interpolation (scipy.interpolate)
- Fourier Transforms (scipy.fftpack)
- Signal Processing (scipy.signal)
- Linear Algebra (scipy.linalg)
- Sparse Eigenvalue Problems with ARPACK
- Compressed Sparse Graph Routines (scipy.sparse.csgraph)
- Spatial data structures and algorithms (scipy.spatial)
- Statistics (scipy.stats)
- Multidimensional image processing (scipy.ndimage)
- File IO (scipy.io)